sonar.projectKey=devops-ecommerce-platform
sonar.projectName=DevOps E-Commerce Platform

sonar.sources=application/backend/src
sonar.tests=application/backend/tests

sonar.javascript.lcov.reportPaths=application/backend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.sourceEncoding=UTF-8
